const assert = require("node:assert/strict");
const { parseTikz, updateTikz, boundaryOffset } = require("./core.js");
const source = String.raw`\node[draw, minimum width=2cm] (a) at (1,-2.5) {Hello};
\node[draw] (b) at (4,3) {World};
\draw[->] (a) -- (b);`;
const parsed = parseTikz(source);
assert.equal(parsed.nodes.length, 2);
assert.equal(parsed.edges.length, 1);
assert.deepEqual([parsed.nodes[0].x, parsed.nodes[0].y, parsed.nodes[0].width], [1, -2.5, 2]);
parsed.nodes[0].x = 2.25;
parsed.nodes[0].height = 1.5;
const output = updateTikz(source, parsed.nodes);
assert.match(output, /\(a\) at \(2\.25,-2\.5\)/);
assert.match(output, /minimum height=1\.5cm/);
parsed.nodes[0].shape = "diamond";
parsed.nodes[0].fill = "blue!20";
parsed.nodes[0].stroke = "blue!70!black";
parsed.nodes[0].label = "Updated label";
parsed.nodes[0].fontFamily = "sans";
parsed.nodes[0].fontSize = 14;
parsed.nodes[0].borderWidth = 1.2;
const styled = updateTikz(source, parsed.nodes);
assert.match(styled, /draw=blue!70!black/);
assert.match(styled, /fill=blue!20/);
assert.match(styled, /diamond/);
assert.match(styled, /\{Updated label\}/);
assert.match(styled, /font=\\sffamily\\fontsize\{14\}\{16\.8\}\\selectfont/);
assert.match(styled, /line width=1\.2pt/);
const reparsed = parseTikz(styled);
assert.equal(reparsed.nodes[0].fontFamily, "sans");
assert.equal(reparsed.nodes[0].fontSize, 14);
assert.equal(reparsed.nodes[0].borderWidth, 1.2);
assert.deepEqual(boundaryOffset("rectangle", 100, 50, 200, 0), { x: 50, y: 0 });
assert.deepEqual(boundaryOffset("ellipse", 100, 50, 0, 200), { x: 0, y: 25 });
assert.deepEqual(boundaryOffset("diamond", 100, 100, 50, 50), { x: 25, y: 25 });
console.log("core parser tests passed");
